=== svn2github/netperf4/trunk/src/netperf_docs.dtd
<?xml version="1.0" encoding="utf-8" ?>
<!-- Contains Declarations for three types of netperf documents:
        netperf configuration file
        netperf commands
        netperf message
     
     all three document types share common element declarations
     which are contained in this dtd file -->

<!-- default entity definitions these may be changed as desired -->

<!ENTITY % default.family	'"AF_INET"' >
<!ENTITY % default.host		'"localhost"' >
<!ENTITY % default.npservice	'"netperf4"' >
<!ENTITY % default.tstservice	'"0"' >
<!ENTITY % default.socksize	'"32"' >
<!ENTITY % default.msgsize     	'"4"' >
<!ENTITY % default.units     	'"KB"' >
<!ENTITY % default.reqsize     	'"1"' >
<!ENTITY % default.rspsize     	'"1"' >
<!ENTITY % default.width     	'"0"' >
<!ENTITY % default.align     	'"8"' >
<!ENTITY % default.offset     	'"0"' >
<!ENTITY % default.no_delay    	'"0"' >


     
<!-- Changeing the definition of any configuration file entity or element
     below this comment may require a code change.  sgb 2003-10-11 -->

<!-- netperf configuration document unique elements -->

<!ELEMENT netperf (netserver)+ >
<!ATTLIST netperf
  xmlns           CDATA    #FIXED    "http://www.netperf.org/ns/netperf"
>

<!ELEMENT netserver (test)+ >
<!ATTLIST netserver
  nid             ID                 #REQUIRED
  family          ( AF_INET | AF_INET6 | AF_UNSPEC )  %default.family;
  remote_service  CDATA                               %default.npservice;
  remote_host     CDATA                               %default.host;
  local_service   CDATA                               %default.npservice;
  local_host      CDATA                               %default.host;
>



<!-- netperf message document unique elements -->

<!ELEMENT message (
  (clear_stats) |
  (cleared) |
  (configured) |
  (die) |
  (dead) |
  (error) |
  (get_stats) |
  (idle) |
  (idled) |
  (initialized) |
  (interval) |
  (close) |
  (closed) |
  (load) |
  (loaded) |
  (measure) |
  (measuring) |
  (snap) |
  (stats) |
  (sys_stats) |
  (test) |
  (test_stats) |
  (version) 
) >
<!ATTLIST message 
  xmlns           CDATA    #FIXED    "http://www.netperf.org/ns/netperf"
  tonid           ID       #REQUIRED 
  fromnid         CDATA    #REQUIRED 
>


<!-- netperf command document unique elements -->

<!ELEMENT commands (
  (clear_stats) |
  (close) |
  (create_test_set) |
  (delete_test_set) |
  (die) |
  (exec_local) |
  (exec_remote) |
  (exit) |
  (get_stats) |
  (idle) |
  (init) |
  (load) |
  (measure) |
  (report_stats) |
  (show) |
  (wait) 
)+ >
<!ATTLIST commands
  xmlns         CDATA    #FIXED    "http://www.netperf.org/ns/netperf"
>
  
<!-- Wait until the specified test or all tests change either to the
     requested state or to an error state. Once tests have completed
     desired state changes wait the specified number of seconds -->
<!ELEMENT wait EMPTY >
<!ATTLIST wait
  tid		CDATA	#REQUIRED
  seconds	CDATA	#IMPLIED
>

<!ELEMENT create_test_set EMPTY >
<!ATTLIST create_test_set
  set_name	ID	#REQUIRED
  tests_in_set  CDATA   #REQUIRED
>
<!-- tests_in_set is a list of test_ids which are to be included in the
     named test set.  Individual ids are seperated by white space. The
     list of tests can also contain a range specifier a range specifier
     is test_id:test_id.  The range will include all tests between and
     including the specified tests. -->

<!ELEMENT delete_test_set EMPTY >
<!ATTLIST delete_test_set
  set_name	ID	#REQUIRED
>

<!ELEMENT show_test_set EMPTY >
<!ATTLIST show_test_set
  set_name	ID	#REQUIRED
>



<!-- shared elements for netperf documents -->

<!ELEMENT dependson EMPTY >
<!ATTLIST dependson
  testid	IDREF   #REQUIRED
  netserverid	IDREF   #REQUIRED
>

<!ELEMENT error ( #PCDATA ) >
<!ATTLIST error
  tid           ID      #REQUIRED
  err_rc	CDATA	#REQUIRED
  err_fn	CDATA	#IMPLIED
  err_str	CDATA	#IMPLIED
  err_no	CDATA	#IMPLIED
>

<!ELEMENT exit EMPTY >

<!ELEMENT host EMPTY >
<!ATTLIST host
  name		CDATA	"localhost"
  family	( AF_INET | AF_INET6 | AF_UNSPEC ) "AF_INET"
  port		CDATA	#REQUIRED
>

<!ELEMENT test ((dependson | dependency_data)?, (socket_args | unknown )?,
                 (dns_args)? ) >
<!ATTLIST test
  xmlns         CDATA   #FIXED    "http://www.netperf.org/ns/netperf"
  tid           ID      #REQUIRED
  test_name     CDATA   "send_tcp_stream"
  library       CDATA   #REQUIRED
  test_clear    CDATA   #IMPLIED
  test_stats    CDATA   #IMPLIED
  test_decode   CDATA   #IMPLIED
>
<!-- test_name
     The attributes allow definition of different function symbol names.
     The function name used for the test function called by netperf4 when
     starting the test is the value specified for test_name. -->
<!-- test_clear is used to specify the name of the function to call to
     clear the statics counters for the test.  If test_clear is not specified
     the default function name will be used which is the concatination of the 
     test_name with "_clear_stats" -->
<!-- test_stats is used to specify the name of the function to call to
     get the statics counters for the test.  If test_stats is not specified
     the default function name will be used which is the concatination of the 
     test_name with "_get_stats" -->
<!-- test_decode is used to specify the name of the function to call to decode,
     accumulate, and report the statics counters for the tests in the library.
     If test_decode is not specified the default function name will be used
     which is the concatination of the test_name with "_decode_stats" -->

<!ELEMENT unknown (#PCDATA) >

<!ELEMENT version EMPTY >
<!ATTLIST version
  vers          CDATA   #REQUIRED
  updt          CDATA   #REQUIRED
  fix           CDATA   #REQUIRED
>


<!-- prototype elements for netperf documents -->


<!ELEMENT clear_stats EMPTY >
<!ATTLIST clear_stats
  xmlns         CDATA   #FIXED    "http://www.netperf.org/ns/netperf"
  tid           CDATA   #REQUIRED
>


<!ELEMENT cleared EMPTY >
<!ATTLIST cleared
  tid           CDATA   #REQUIRED
>


<!ELEMENT close EMPTY >
<!ATTLIST close
  sid           CDATA           #REQUIRED
  flag          (LOOP | EXIT)   "LOOP"
>


<!ELEMENT closed EMPTY >
<!ATTLIST closed
  flag          (LOOPING | GONE)  #IMPLIED
>


<!ELEMENT configured EMPTY >

<!ELEMENT dependency_data (#PCDATA) >
<!ATTLIST dependency_data
  xmlns         CDATA   #FIXED    "http://www.netperf.org/ns/netperf"
  family        (AF_INET|AF_INET6|AF_UNSPEC)  "AF_INET"
  remote_port   CDATA                         #REQUIRED
  remote_host   CDATA                         #REQUIRED
  use_tcp       (yes | no | true | false)     #IMPLIED
>


<!ELEMENT die EMPTY >
<!ATTLIST die
  xmlns         CDATA   #FIXED    "http://www.netperf.org/ns/netperf"
  tid           CDATA   #REQUIRED
>


<!ELEMENT dead EMPTY >
<!ATTLIST dead
  tid           CDATA   #REQUIRED
>


<!ELEMENT exec_local EMPTY >
<!ATTLIST exec_local
  command       CDATA   #REQUIRED
>

<!-- exec_remote is a security hole and is not implemented -->

<!ELEMENT exec_remote EMPTY >
<!ATTLIST exec_remote
  nid           ID      #REQUIRED
  command       CDATA   #REQUIRED
>


<!ELEMENT get_stats EMPTY >
<!ATTLIST get_stats
  xmlns         CDATA   #FIXED    "http://www.netperf.org/ns/netperf"
  tid           CDATA   #REQUIRED
>


<!ELEMENT idle EMPTY >
<!ATTLIST idle
  xmlns         CDATA   #FIXED    "http://www.netperf.org/ns/netperf"
  tid           CDATA   #REQUIRED
>

<!ELEMENT idled EMPTY >
<!ATTLIST idled
  xmlns         CDATA   #FIXED    "http://www.netperf.org/ns/netperf"
  tid           CDATA   #REQUIRED
>


<!ELEMENT initialized (dependency_data)? >
<!ATTLIST initialized
  tid           ID      #REQUIRED
>


<!ELEMENT interval EMPTY >
<!ATTLIST interval 
  tid           ID      #REQUIRED
  seconds       CDATA   "10"
>


<!ELEMENT load EMPTY >
<!ATTLIST load
  xmlns         CDATA   #FIXED    "http://www.netperf.org/ns/netperf"
  tid           CDATA   #REQUIRED
>


<!ELEMENT loaded EMPTY >
<!ATTLIST loaded
  tid           ID      #REQUIRED
>


<!ELEMENT measure EMPTY >
<!ATTLIST measure 
  xmlns         CDATA   #FIXED    "http://www.netperf.org/ns/netperf"
  tid           CDATA   #REQUIRED
  seconds       CDATA   "10"
>

<!ELEMENT measuring EMPTY >
<!ATTLIST measuring 
  tid           ID      #REQUIRED
>

<!-- if output_file is not specified output defaults to stdout -->
<!-- The attributes command_file and output_file are for a looped tests -->
<!-- The attributes interval and confidence are for checking confidence
     for reported test results.  min_count must be specified to check
     confidence. -->
<!-- Interval is the desired percentage range around the mean for which
     the confidence level is calculated.   example 0.05 is mean +/- 2.5%
     The default value for interval is 0.05  -->
<!-- confidence is the desired confidence level which measured results
     fall within the interval around the reported measured mean. 
     The default value for confidence is 99% -->

<!ELEMENT report_stats (
  (clear_stats) |
  (create_test_set) |
  (delete_test_set) |
  (exec_local) |
  (exec_remote) |
  (get_stats) |
  (idle) |
  (init) |
  (load) |
  (measure) |
  (show) |
  (wait)
)* >
<!ATTLIST report_stats 
  test_set      CDATA   #REQUIRED
  library       CDATA   #REQUIRED
  function      CDATA   #REQUIRED
  report_flags  CDATA   #IMPLIED
  output_file   CDATA   #IMPLIED
  max_count     CDATA   #IMPLIED
  min_count     CDATA   #IMPLIED
  interval      CDATA   #IMPLIED
  confidence  (50 | 70 | 80 | 90 | 95 | 98 | 99 | 99.8 | 99.9) #IMPLIED
>

<!ELEMENT snap EMPTY >
<!ATTLIST snap tid  IDREF  "t_all" >


<!ELEMENT stats (sys_stats, (test_stats)+) >

<!ELEMENT received_stats ((test_stats)+) >


<!ELEMENT sys_stats ( #PCDATA | per_cpu_stats )* >
<!ATTLIST sys_stats 
  tid            ID      #REQUIRED
  elapsed_sec    CDATA   #IMPLIED
  elapsed_usec   CDATA   #IMPLIED
  time_sec       CDATA   #IMPLIED
  time_usec      CDATA   #IMPLIED
  method         CDATA   #IMPLIED
  number_cpus    CDATA   #IMPLIED
  calibration    CDATA   #IMPLIED
  idle_count     CDATA   #IMPLIED
  user_count     CDATA   #IMPLIED
  sys_count      CDATA   #IMPLIED
  int_count      CDATA   #IMPLIED
  other_count    CDATA   #IMPLIED
>

<!ELEMENT per_cpu_stats ( #PCDATA ) >
<!ATTLIST per_cpu_stats 
  cpu_id         CDATA   #REQUIRED
  calibration    CDATA   #IMPLIED
  idle_count     CDATA   #IMPLIED
  user_count     CDATA   #IMPLIED
  sys_count      CDATA   #IMPLIED
  int_count      CDATA   #IMPLIED
  other_count    CDATA   #IMPLIED
>

<!ELEMENT test_stats ( #PCDATA ) >
<!ATTLIST test_stats 
  tid            ID      #REQUIRED
  elapsed_sec    CDATA   #IMPLIED
  elapsed_usec   CDATA   #IMPLIED
  time_sec       CDATA   #IMPLIED
  time_usec      CDATA   #IMPLIED
  cntr0_value    CDATA   #IMPLIED
  cntr1_value    CDATA   #IMPLIED
  cntr2_value    CDATA   #IMPLIED
  cntr3_value    CDATA   #IMPLIED
  cntr4_value    CDATA   #IMPLIED
  cntr5_value    CDATA   #IMPLIED
  cntr6_value    CDATA   #IMPLIED
  cntr7_value    CDATA   #IMPLIED
  cntr8_value    CDATA   #IMPLIED
  cntr9_value    CDATA   #IMPLIED
  cntrA_value    CDATA   #IMPLIED
  cntrB_value    CDATA   #IMPLIED
  cntrC_value    CDATA   #IMPLIED
  cntrD_value    CDATA   #IMPLIED
  cntrE_value    CDATA   #IMPLIED
  cntrF_value    CDATA   #IMPLIED
  info0_value    CDATA   #IMPLIED
  info1_value    CDATA   #IMPLIED
  info2_value    CDATA   #IMPLIED
  info3_value    CDATA   #IMPLIED
  info4_value    CDATA   #IMPLIED
  info5_value    CDATA   #IMPLIED
  info6_value    CDATA   #IMPLIED
  info7_value    CDATA   #IMPLIED
  info8_value    CDATA   #IMPLIED
  info9_value    CDATA   #IMPLIED
  infoA_value    CDATA   #IMPLIED
  infoB_value    CDATA   #IMPLIED
  infoC_value    CDATA   #IMPLIED
  infoD_value    CDATA   #IMPLIED
  infoE_value    CDATA   #IMPLIED
  infoF_value    CDATA   #IMPLIED
>


<!ELEMENT socket_args EMPTY >
<!ATTLIST socket_args
  family          ( AF_INET | AF_INET6 | AF_UNSPEC )  %default.family;
  local_service     CDATA    %default.tstservice;
  local_host        CDATA    %default.host;
  fill_file         CDATA    #IMPLIED
  send_buffer_size  CDATA    %default.socksize;
  send_buffer_units (B | kB | KB | mB | MB | gB | GB)  %default.units;
  recv_buffer_size  CDATA    %default.socksize;
  recv_buffer_units (B | kB | KB | mB | MB | gB | GB)  %default.units;
  no_delay          CDATA    %default.no_delay;
  send_size         CDATA    %default.msgsize;
  send_size_units   (B | kB | KB | mB | MB | gB | GB)  %default.units;
  recv_size         CDATA    %default.msgsize;
  recv_size_units   (B | kB | KB | mB | MB | gB | GB)  %default.units;
  req_size          CDATA    %default.reqsize;
  rsp_size          CDATA    %default.rspsize;
  port_min          CDATA    #IMPLIED
  port_max          CDATA    #IMPLIED
  send_width        CDATA    %default.width;
  recv_width        CDATA    %default.width;
  send_align	    CDATA    %default.align;
  recv_align	    CDATA    %default.align;
  send_offset       CDATA    %default.offset;
  recv_offset       CDATA    %default.offset;
>

<!ELEMENT dns_args EMPTY >
<!ATTLIST dns_args
  max_outstanding   CDATA    #IMPLIED
  timeout           CDATA    #IMPLIED
>
                      
<!-- Element definitions for variable sized data tests  -->

<!ELEMENT work_load_description (pattern, distribution?)* >
<!ATTLIST work_load_description
  name              CDATA    #REQUIRED
>


<!ELEMENT pattern (pattern_entry)* >
<!ATTLIST pattern
  index             CDATA    #REQUIRED
>


<!ELEMENT pattern_entry EMPTY >
<!ATTLIST pattern_entry
  req_size          CDATA    #IMPLIED
  rsp_size          CDATA    #IMPLIED
>


<!ELEMENT distribution (distribution_entry)* >
<!ATTLIST distribution
  dist_key          CDATA    #IMPLIED
>


<!ELEMENT distribution_entry EMPTY >
<!ATTLIST distribution_entry
  next_pattern      CDATA    #IMPLIED
  number            CDATA    #IMPLIED
>

=== svn2github/netperf4/trunk/src/stephen_config.xml
<?xml version="1.0" standalone="no" ?>
<!DOCTYPE netperf SYSTEM "../netperf/netperf_docs.dtd" >        
<netperf xmlns="http://www.netperf.org/ns/netperf">
<!-- This is just another boring comment -->
<netserver nid="n1" >
  <test tid="t0"
    test_name = "hpux_sys_stats"
    library   = "netsysstats.sl" >
  </test>
  <test tid="t1"
    test_name = "send_tcp_stream"
    library   = "nettest_bsd.sl" >
    <dependson testid="t2" netserverid="n1" />
    <socket_args
      send_buffer_size = "128"
      recv_buffer_size = "128"
      send_size        = "32"  />
  </test>
  <test tid="t2"
    test_name = "recv_tcp_stream"
    library = "nettest_bsd.sl" >
    <socket_args
      send_buffer_size = "128"
      recv_buffer_size = "128" />
  </test>
  <test tid="t3"
    test_name = "send_tcp_rr"
    library   = "nettest_bsd.sl" >
    <dependson testid="t4" netserverid="n1" />
    <socket_args />
  </test>
  <test tid="t4"
    test_name = "recv_tcp_rr"
    library = "nettest_bsd.sl" >
    <socket_args />
  </test>
</netserver>
</netperf>
